### ISSUE TITLE
Add Testing

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-cldr#16]
We should have some basic unit tests like:

```php
$cldr = new WP_CLDR( 'fr' );
$germany_in_french = $cldr->_territory( 'DE' );
$test->assertEquals( 'Allemagne', $germany_in_french );
```

and:

```php
$canadian_french_in_english = $cldr->_language( 'fr-CA' , 'en' );
$test->assertEquals( 'Canadian French', $canadian_french_in_english );
```

..etc.

**Comment by stuwest** [comment]
+1. Aside from checking our code, CLDR [has new releases every six months] (http://cldr.unicode.org/#TOC-General-Schedule-) and we'd want enough tests to feel comfortable about a new release before we include it. Next release (v.27) is scheduled for March 15 or so.
