### ISSUE TITLE
function naming conventions

### ISSUE THREAD

**Issue by stuwest** [Automattic/wp-cldr#30]
I'm working on some new functions to extract supplemental data from CLDR including `_postal_code_regex`, `_telephone_code`, `_currency_code`, `_plural_rules`, `_territories_contained`, `_first_day_of_week`. Question around naming conventions. There are a bunch of items with a master identifier and then a few attributes e.g.:

```
territory -- territory_code, territory_name
currency -- currency_code, currency_name, currency_symbol
language -- language_code, language_name
```
Should we always include the attribute specifier in function/variable names? For example, should we change our current function `_territory` to `_territory_name`? That feels clearer to me, even if longer.

**Comment by jblz** [comment]
I think we should mirror the CLDR data keys as much as possible.

I noticed this changed for `_currency_name` at some point.  Seems reasonable to do this for the rest of the cases like it.

**Comment by stuwest** [comment]
Agreed.  CLDR uses `localeDisplayNames` as a data key so if we want to match exactly we could use e.g. `currency_display_name`. That feels long so I'd lean toward just `currency_name` but could be sold on including `_display` if we want to be super precise in matching CLDR.

**Comment by stuwest** [comment]
addressed in https://github.com/Automattic/wp-cldr/issues/34
