### ISSUE TITLE
To `get_` or not to `get_`?

### ISSUE THREAD

**Issue by stuwest** [Automattic/wp-cldr#31]
how do you feel about `get_` in function names? Should `_currency_code` become `_get_currency_code`?  I generally read the underscore as a "get" so it doesn't feel necessary to me but better to confirm now than later given they're externally facing.

**Comment by jblz** [comment]
Heh, I was actually just considering dropping the preceding `_` from the public helper functions altogether for easier calling.

I don't think adding a `get_` adds much here.

**Comment by stuwest** [comment]
hah. I think we were both reacting to the same underlying issue -- the `_` at the beginning of the public helper functions is cool as a subtle reference to gettext but is awkward. Given this will typically be called from within an object (e.g. $cldr->territory_name` seems we could do away with it.

**Comment by stuwest** [comment]
discussion moved to https://github.com/Automattic/wp-cldr/issues/32
