### ISSUE TITLE
Prefer shorter country names?

### ISSUE THREAD

**Issue by stuwest** [Automattic/wp-cldr#36]
A few of the default CLDR territory names feel long and unnatural to me (e.g. `Hong Kong SAR China` and `Macau SAR China`). The data set includes shorter variations for seven territories e.g. in English:

[BA] => Bosnia & Herzegovina
[BA-alt-short] => Bosnia
[HK] => Hong Kong SAR China
[HK-alt-short] => Hong Kong
[MO] => Macau SAR China
[MO-alt-short] => Macau
[MM] => Myanmar (Burma)
[MM-alt-short] => Myanmar
[PS] => Palestinian Territories
[PS-alt-short] => Palestine
[GB] => United Kingdom
[GB-alt-short] => U.K.
[US] => United States
[US-alt-short] => U.S.

Should we default to return some or all of the available `-alt-short` variants? We could add an optional parameter to return the longer ones.

Generally I'd rather not try to second guess CLDR but it seems like this is an area others have struggled with too. See the [translation guidelines from CLDR which addresses the rationale behind these] (http://cldr.unicode.org/translation/country-names#TOC-Sensitive-Names) and [a review of how Google handles them] (http://people.oii.ox.ac.uk/hanteng/2014/05/24/google-uses-the-unicodes-cldr-common-locale-data-repository-for-its-listed-country-names-selectively/). 

cc @stephanethomas

**Comment by stephanethomas** [comment]
I wonder if the same applies in languages other than English, i.e. if the short version is more appropriate than the full one (e.g. I remember the short version of `United States` in French is `É.U` which is something that we don't see that often in this language).

**Comment by stuwest** [comment]
I'm going to close this under the principle that:

> I'd rather not try to second guess CLDR

Anyone who wants to use the shorter version of these can choose too just e.g. by selecting `HK-alt-short` instead of `HK`.
