### ISSUE TITLE
Methods meant to be class-internal should be declared private

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-cldr#40]
These almost certainly should be private:
* [`get_cldr_json_package`](https://github.com/Automattic/wp-cldr/blob/c0e269434e7ba97fd70e1cc97ff3065536f64737/class.wp-cldr.php#L108)
* [`get_cldr_json_file`](https://github.com/Automattic/wp-cldr/blob/c0e269434e7ba97fd70e1cc97ff3065536f64737/class.wp-cldr.php#L126)
* [`initialize_locale_bucket`](https://github.com/Automattic/wp-cldr/blob/c0e269434e7ba97fd70e1cc97ff3065536f64737/class.wp-cldr.php#L144)

...maybe others, but this is a start :)

**Comment by stuwest** [comment]
What's the smart way to handle around unit testing? Right now I have a bunch of test call dysfunctions directly to make sure we're getting the expected behavior.

**Comment by stuwest** [comment]
What's the smart way to handle around unit testing? Right now I have a bunch of test call dysfunctions directly to make sure we're getting the expected behavior.
