### ISSUE TITLE
json files not loading due to folder name mismatch

### ISSUE THREAD

**Issue by vercotux** [Automattic/wp-cldr#42]
The *get_cldr_json_file* function is trying to load the JSON files from a folder called *cldr-27* when the folder included in the project is called *cldr-v27*, which obviously does not work. The CLDR_VERSION constant is defined as "27", without the letter **v**. So either change the const or add the "v" when building the path.

See: https://github.com/Automattic/wp-cldr/blob/master/class.wp-cldr.php#L124

**Comment by stuwest** [comment]
also added a Travis CI integration in https://github.com/Automattic/wp-cldr/commit/325d6fcf8899c3968265040937a833114c410a79 for regular unit testing
