### ISSUE TITLE
use hyphen in class.wp-cldr.php?

### ISSUE THREAD

**Issue by stuwest** [Automattic/wp-cldr#59]
looks like the [WordPress coding standards naming conventions](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions) say we should use a hyphen in the class file name:

> Class file names should be based on the class name with class- prepended and the underscores in the class name replaced with hyphens, for example WP_Error becomes:
> 
> `class-p-error.php`
> 
> This file-naming standard is for all current and new files with classes. There is one exception for three files that contain code that got ported into BackPress: class.wp-dependencies.php, class.wp-scripts.php, class.p-styles.php.

Does that make sense as a change @jblz?

**Comment by jblz** [comment]
It makes sense to follow the standards ( even if I personally disagree with them :) )
