### ISSUE TITLE
Add other L10n helper capabilities?  (was change plugin name)

### ISSUE THREAD

**Issue by stuwest** [Automattic/wp-cldr#63]
Here's one more breaking change to think about before we release first version (along with #60 and #59).

Should we change the name of plugin?  `wp-cldr` is specific, but also cryptic to many developers and limiting in terms of the ultimate value it could add.

One alternative would be something broader like "WP Localization Helper" `wp-l10n-helper`.

cc @akirk and @yoavf who might have interesting points of view.

**Comment by jblz** [comment]
I don't really have a strong opinion here. I guess it's a matter of where we see the plugin going long-term. i.e. if we anticipate integrating some other library or functionality outside of / beyond CLDR, it def makes sense to broaden the name.

On the other hand, if we want to keep it strictly targeted at being the best CLDR-specific WordPress plugin in all the land, I think I prefer its current name from a "Say what you mean" perspective.

**Comment by stuwest** [comment]
Yeah I think we leave as is for now.

The one thing I know already I'd like to have is some kind of linter for i18n stuff.... but that's probably better done as a `phpcs` ruleset.

**Comment by akirk** [comment]
I'd also vote for leaving the name as it is until you add a second source of localization information.

**Comment by stuwest** [comment]
Yep. Other things I've thought would be handy to include are a) some kind of GEOIP service (hitting http://public-api.wordpress.com/geo/ perhaps) and b) some kind of linting for WordPress i18n.

**Comment by stuwest** [comment]
plugin submitted to repo, so no going back on the name/slug now. :)
