### ISSUE TITLE
Test process should be documented

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-cldr#65]
I don't see any explicit instructions as to how to run the test suite. If there aren't already any that I've missed, it'd be good to add some :)

**Comment by stuwest** [comment]
Good idea. It's pretty simple I'd say something like:

> The class included a set of PHPUnit tests. To run them, call `phpunit` from the plugin directory. 

Does that cover it? Where do you think that belongs? in the README?  or the class docblock?  both?

**Comment by jblz** [comment]
I think the README(s) would be best.

**Comment by stuwest** [comment]
fixed in https://github.com/Automattic/wp-cldr/commit/ca4395f66d8e274c085d34bbb2b96eb003bfd948
