### ISSUE TITLE
Update to latest CLDR

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-cldr#88]
Current version at time of writing this is <s>30.0.3</s> 31.0.1.

http://cldr.unicode.org/index/downloads/cldr-31

[cldr-json](https://github.com/unicode-cldr/cldr-json) looks to be at <s>30.0.2</s> 31.0.0.

**Comment by stuwest** [comment]
yeah the underlying CLDR data is updated every six months. Not always a lot of substantive changes but we should catch up the repo at least every other update cycle.
